pipeline:
  publish:
    image: plugins/npm
    settings:
      username: $${NPM_USERNAME}
      token: $${NPM_TOKEN}
      email: $${NPM_EMAIL}
    secrets: [NPM_USERNAME, NPM_TOKEN, NPM_EMAIL]
    when:
      event: tag

